import './globals.css'

import type { Metadata } from 'next'
import { Dosis } from 'next/font/google'

import { Header } from '@/components/header'

const dosis = Dosis({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Meta diária',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${dosis.className} flex h-screen w-full flex-col bg-neutral-900 text-white`}
      >
        <Header />
        {children}
      </body>
    </html>
  )
}
